# Generated by Django 3.2.9 on 2022-01-14 02:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('n_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('adhar_num', models.IntegerField()),
                ('phone_num', models.IntegerField()),
                ('land_survey_num', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Tamota', 'T'), ('Mirchi', 'M'), ('Vanyakaya', 'V'), ('Chendu Malli', 'CM')], max_length=50)),
                ('quatity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farmer_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='n_app.farmer')),
                ('nursary_p', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='n_app.nursary')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='n_app.product')),
            ],
        ),
    ]
