# Generated by Django 3.2.9 on 2022-01-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n_app', '0002_auto_20220114_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(blank=True, default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
