# Generated by Django 3.2.3 on 2022-03-02 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('n_app', '0003_auto_20220117_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursary',
            name='columns',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nursary',
            name='nursary_photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='nursary_photo/'),
        ),
        migrations.AddField(
            model_name='nursary',
            name='rows',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nursary',
            name='visiting_card',
            field=models.ImageField(blank=True, default='default.png', upload_to='visting_card/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='dp',
            field=models.ImageField(blank=True, default='default.png', upload_to='dp/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=10000)),
                ('status', models.CharField(choices=[('E', 'Empty'), ('A', 'Available'), ('B', 'Booked'), ('C', 'Completed')], default='E', max_length=50)),
                ('nursary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='n_app.nursary')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='n_app.bed'),
        ),
    ]
